services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: pip install -r requirements-prod.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free